### ISSUE TITLE
[GIP] introducing a message broker

### ISSUE THREAD

**Issue by pmauduit** [georchestra/improvement-proposals#6]
### Who ?

Camptocamp

### Target Module

Every modules (at least, potentially)

### What ?

The purpose of this GIP is to introduce a message broker, to facilitate further needed communication across geOrchestra modules.

### Why ?

At the begining, the idea behind geOrchestra was to take several existing independant piece of softwares (geonetwork, geoserver), implementing some new webapps (extractorapp, viewer), and putting them together using a common entrypoint (security-proxy).
It was sometimes hard to make sure every components could comply with this "ecosystem", and some implementation choices had to be made (e.g. removing groups from the LDAP, and getting for roles and organisations, or more recently rewriting the way the group synchronisation in geonetwork to decouple it from the LDAP server).

With the coming georchestra-gateway, and the need for supporting external third-party identity providers, we are in the need for creating accounts (for example to keep track of external ones) into the LDAP. But is it the gateway's role ? Or should it be delegated to the Console ? What if we don't want to couple the gateway to the console ?

Hence the idea of introducing a message broker in the solution:  to get back to the previous example, an "external user creation" could be a message being emitted from the gateway, which could be consumed by another application (console, or maybe another one) which would take care of the actual account creation.

### How ?

Considering that geOrchestra is mainly a set of components written in Java with the Spring Framework, using something compatible with it sounds relevant. In term of potential software available, it sounds that RabbitMQ could be a relevant choice.

### Any potential pitfalls and ways to circumvent them ?

Adding a new piece of software in an infrastructure will obviously complexify it. On the other hand, RabbitMQ is available as a docker image as well as a debian package.

Also making every components which could take benefit from a message broker aware of it in one go is probably not the way to do, but we could probably go step by step on it, begining with the gateway's current need exposed previously as an example.

### When ?

At the same time as when the georchestra gateway will be introduced.

### State of the vote:

| PSC members              | vote |
|-------------------------:|------|
| Fabrice Phung               | +1     |
| François Van Der Biest   | +1  |
| Pierre Mauduit              | +1  |
| Landry Breuil                 | +1  |
| Stéphane Mével-Viannay   |  0  |
| Maël Reboux                | +1  |
| Pierre Jégo                   | +1  |
| Jean Pommier              | +1  |
| Catherine Piton-Morales  | +1  |

Adopted on 2023-10-10.

**Comment by edevosc2c** [comment]
My idea: I think PostgreSQL can be a viable solution as a message broker service, there will never be enough messages sent per seconds on a geOrchestra platform to the point that it will saturate PostgreSQL in order to consider a "faster solution" like RabbitMQ or Kafka.

Not adding a new dependency is going towards reducing the possible infrastructure maintenance.

Here is a good article that explain for "low demand" projects, PostgreSQL can be used instead of Kafka/RabbitMQ: https://dagster.io/blog/skip-kafka-use-postgres-message-queue

And another article that explain in technical terms how to implement such solution: https://www.crunchydata.com/blog/message-queuing-using-native-postgresql

**Comment by fvanderbiest** [comment]
I'm +1 on the broker introduction, and let the experts choose between PostGreSQL and RabbitMQ.

**Comment by jeanpommier** [comment]
+1 for the broker, seems like something that would also be useful when integrating third party software

I have not experience, hence no opinion about one choice or the other

**Comment by pmauduit** [comment]
For now we are 3 in favor, any objection  @fphg @landryb @smevel @MaelREBOUX @pierrejego @catmorales ?

**Comment by landryb** [comment]
i'd have preferred something that relies on an existing dependency as @edevosc2c mentioned (eg using psql) but since the code for using rabbitmq is already written... whatever :)

i don't see much research into what this would really bring to the platform, but i definitely see some use for it (eg reacting upon events fired by various components, which i do for now by subscribing to ldap syncrepl messages..)

- a metadata was created/modified/deleted/viewed
- a layer was created/modified/deleted/viewed
- a map was created/modified/deleted/viewed
- an org was created/modified/deleted
- an user was created/modified/deleted

but.. to fully gain from that, it'd mean adding the concept of events/messages to upstream projects:
- geonetwork
- geoserver
- mapstore

each of them might have their own idea about how to achieve it..

so i'm +1 on the concept, but -0 on the addition of rabbitmq. Not voting -1 because i don't have time to work on "something better", but i'd definitely prefer if psql could simply be reused.. after all we already store admin logs for the console in psql ;)

**Comment by pmauduit** [comment]
> but since the code for using rabbitmq is already written... whatever :)

As explained in the mail to the georchestra list, this is purely exploratory for now: a PoC is being made using the georchestra-gateway which has not even replaced the security-proxy for now. Also RabbiMQ sounds a relevant choice anyway because it is already packaged for both worlds (docker & debian, which are the main "distributions" being used to deploy geOrchestra), and it is quite well supported by spring.

**Comment by fphg** [comment]
Like FVDB I think the broker would be a nice addition for Georchestra. However, I have a few questions.

- Does this affect the principle of modularity, which means that a Georchestra module can be used independently of the others? 
- What impact on hosting?

**Comment by fvanderbiest** [comment]
My POV below.

> * Does this affect the principle of modularity, which means that a Georchestra module can be used independently of the others?

The addition does not affect modularity, since we'll make sure modules can start & work as expected if the broker is down or unavailable.
A message broker is a good pattern for loosely coupled modules (see eg https://learn.microsoft.com/en-us/azure/architecture/patterns/category/messaging)


> * What impact on hosting?

As Pierre said, one more debian package dependency - low ressources required (https://www.rabbitmq.com/production-checklist.html)

**Comment by fphg** [comment]
Then I'm +1
IMHO the discussion should take place on the mailing list. If it doesn't, a short summary of this thread will be welcomed on the list (btw thanks @pmauduit for the notification)

**Comment by pierrejego** [comment]
I can't see for the moment real fonctionnal interest  in the message broker but it will for sure make geOrchestra more modular. So +1

**Comment by catmorales** [comment]
I didn't understand all the subtleties, but +1 for testing. It seems good for geOrchestra administration.

**Comment by pmauduit** [comment]
PSC members are 77.78% in favor of this one (but after 3 weeks, instead of 2, following the rules). If we consider my last call for vote as a prolongation request, then this one should be good to go.

**Comment by jeanpommier** [comment]
@MaelREBOUX @smevel  we need your votes here (need to know if someone votes -1, although i guess you would already have voted in this case)

**Comment by MaelREBOUX** [comment]
Hello.

Not expert in Message Queue Systems. From my point of view, for geOrchestra :

- If voted, we should decide if this module is mandatory or not in the geOrchestra SDI. If not mandatory, admins could decide to not install it. If not installed, others modules should work without it. Admin and installation guides should clarify that.
- However a feature like Message Queue System in geOrchestra would be a nice feature for a modern and up-to-date SDI
- I don't know if RabbitMQ Support is good or not. Sounds pretty however.

So : +1

@fphg in a near future we will not longer use PostgreSQL to store the statistics or analytics. See https://github.com/georchestra/analytics/ 

Note for @jeanpommier : surprised to see a merge as the GIP is still in discussion. It breaks the rules.... And we mix again discussion and call for vote.

**Comment by MaelREBOUX** [comment]
Tracking point 2024-01 : some code exists in the master branch but the functionality is disabled by default.

**Comment by fvanderbiest** [comment]
The code has been contributed to `master` for geOrchestra 24.0 with the following PRs: https://github.com/georchestra/georchestra/pulls?q=is%3Apr+rabbitmq+is%3Aclosed

New config options have been added to the datadir as well, see https://github.com/georchestra/datadir/blob/baac8e9bbf93ba206c96d533aa0b8687d6703269/default.properties#L78-L93

And indeed, by default there's no need to deploy rabbitmq.
Thos who do will get a better integration of the gateway and console applications.

Closing here.
