### ISSUE TITLE
[GIP] A new data API

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/improvement-proposals#7]
### Who ?

Camptocamp with funding from Métropole Européenne de Lille (MEL)

### Target Module

The proposal is about a new, optional module, which exposes an API for geo and non geo datasets.

### What ?

The data-api module exposes an **OGC API - Features** endpoint to query public datasets.

The main benefit of this addition is the ability to expose non-geo datasets through a standards-compliant API.
Hopefully not falling into the case depicted in this [famous xkcd](https://xkcd.com/927/).

There are no ACL for now, but MEL has projects with regards to this.

### Why ?

Compared to [GeoServer's OGC API extension](https://docs.geoserver.org/main/en/user/community/ogc-api/features/index.html), there are several advantages:

- ability to expose non geo datasets
- no need to declare resources - all resources uploaded to the backend database are exposed by default
- automatic dataset reload in case of changes in the underlying schema
- modern design based on Spring Boot

### How ?

Since this is a standalone API, there's no dependency to consider.

In an upcoming datafeeder evolution (CSV file upload, see georchestra/georchestra#3879), there could be a dependency on this new data api module, since the generated metadata will be configured to point at the dataset served by this data api by default. This will be configurable through the datadir.

### When ?

The API has been developed in the https://github.com/camptocamp/mel-data-api repository and there have been 2 releases to date.

If the community accepts it, it will be migrated to the geOrchestra github organization and the LICENCE will be updated accordingly. It may also be added to the standard deployment method (https://github.com/georchestra/docker).

### State of the vote:

| PSC members              | vote |
|-------------------------:|------|
| Fabrice Phung            | +1     |
| François Van Der Biest   |   +1   |
| Pierre Mauduit           |   +1   |
| Landry Breuil            |  +1 |
| Stéphane Mével-Viannay   |   +1   |
| Maël Reboux              |  +1    |
| Pierre Jégo              |   +1   |
| Jean Pommier             |   +1   |
| Catherine Piton-Morales  |   +1   |

**Comment by pmauduit** [comment]
:+1:

**Comment by fphg** [comment]
Hi

This is a nice feature.
Have some questions and remarks

> The data-api module exposes an OGC API - Features endpoint to query public datasets.

From the data admin point of view : what's a "public dataset" ? A dataset described as public in the catalog ? A dataset with specific permissions ?

> no need to declare resources - all resources uploaded to the backend database are exposed by default

Again, from the data admin pov : a platform may have a lot of different backend databases. IE we can serve datasets from a Postgres or SQLite database. They often are a mix of geo and non-geo tables served "as a query" in GeoServer. How can the module determine which tables should be published and which should not?

Sorry if I misunderstood some points. A user story may help !

**Comment by fvanderbiest** [comment]
> This is a nice feature.

Thanks !

> what's a "public dataset" ?

It's a dataset with no access restrictions, stored in the backend database (currently, the module does not offer any ability to restrict access to the data it exposes).

> How can the module determine which tables should be published and which should not?

The module is configured with a DB connection and a schema (see https://github.com/camptocamp/mel-data-api/?tab=readme-ov-file#running). All tables in the above-mentionned schema are currently published.

> A user story may help !

Example user stories:

- as a data platform user, I upload geo and non geo datasets using datafeeder. I need to share them openly with the rest of the world via public APIs.
- as a data platform admin, I configure vrt-bot to harvest remote datasets (eventually filtering them, or performing minor transformation steps). I'd like to serve these "remixed datasets" to my users with a standard's compliant API.
- my org stores datasets in an internal Oracle database, which are not accessible to the general public. I'd like to foster local innovation by sharing this dataset more openly. (I'll set up an ETL job to push the selected datasets to a database connected with this API)

**Comment by landryb** [comment]
some (technical) feedback first:

- it needs `-DskipTests` to build without the docker ecosystem. otherwise tests obviously fail (as is now often the case in the georchestra ecosystem, sadly):
```
[ERROR] Errors: 
[ERROR]   CollectionsApiImplPostgisTest.setUp:70 » IllegalState Could not find a valid Docker environment. Please see logs and check configuration
[INFO]
[ERROR] Tests run: 19, Failures: 0, Errors: 1, Skipped: 0
```
- builds fine with `./mvnw clean install package -P-docker -DskipTests` and i have a spring-boot jar.
- starting it with `java -Dspring.profiles.active=sample-data -jar /tmp/opendata-ogc-features-1.2-SNAPSHOT-bin.jar` and going to http://localhost:8080/ in a browser correctly redirects to swagger-ui where one can query the default/sample collections.
- starting it with `env POSTGRES_HOST=localhost POSTGRES_DB=georchestra POSTGRES_USER=georchestra POSTGRES_PASSWORD=xxx POSTGRES_SCHEMA=psc java  -Dspring.profiles.active=postgis -jar /tmp/opendata-ogc-features-1.2-SNAPSHOT-bin.jar` it correctly lists the postgis tables in the psc schema of a georchestra instance.
- some usability nit, i first tried `/ogcapi/` then `/ogcapi/collections/` with curl and only got 404's on URLs with a trailing slash:
```
curl -H 'accept: application/json' http://localhost:8080/ogcapi/collections/
{"timestamp":"2024-01-24T08:49:23.847+00:00","status":404,"error":"Not Found","path":"/ogcapi/collections/"}
```
- i haven't looked at the actual ogc api spec nor at what geoserver does/supports, but i know mapserver accepts both (eg https://demo.mapserver.org/cgi-bin/mapserv/localdemo/ogcapi/collections/?f=html with a trailing slash works) - im not sure pg_featureserv does but its doc only advertises `/collections` without a trailing slash.
- there must be a bug somewhere, because in this default setup all href links are starting with `http:/` (missing slash):
```
http:/localhost:8080/ogcapi/collections/avis_partenaires/items?f=geojson
```
and thus browsing via links is broken. what header/env var sets the FQDN used for links ?

on the 'philosophical' side, i'm always saddened by the NIH syndrom and would have thought it more efficient to contribute non-geodata support to the geoserver OGCAPI module, but i understand it might be a larger undertaking.

on the 'consumer-facing'/user story side, maybe it should be stressed somewhere that (afaict since geosolutions-it/MapStore2#9276) mapstore supports opening arbitrary geojson urls, so from a recent datahub deployment one can click on OGCAPI links and see the datasets in mapstore ? otherwise nothing knows how to consume OGCAPI links in georchestra itself..unless i'm mistaken.

generally, :+1: on the idea, since OGCAPI is the future, one way or another :)

**Comment by pmauduit** [comment]
> (as is now often the case in the georchestra ecosystem, sadly)

I tend to agree with you on the fact that geOrchestra should remain agnostic to the docker frenzy, I personnally find acceptable to make use of docker for integration tests, in order to avoid to deploy a whole infrastructure just for the sake of running the testsuite :-/ Mocking everything is hard ...

**Comment by landryb** [comment]
> * there must be a bug somewhere, because in this default setup all href links are starting with `http:/` (missing slash):
> ```
> http:/localhost:8080/ogcapi/collections/avis_partenaires/items?f=geojson
> ```
> and thus browsing via links is broken. what header/env var sets the FQDN used for links ?

reported as camptocamp/mel-data-api#18

**Comment by landryb** [comment]
> I tend to agree with you on the fact that geOrchestra should remain agnostic to the docker frenzy, I personnally find acceptable to make use of docker for integration tests, in order to avoid to deploy a whole infrastructure just for the sake of running the testsuite :-/ Mocking everything is hard ...

i agree with that and totally understand the use of docker for IT, but then it should fallback to not run the tests by default if docker isnt found (or skip the ones that require docker), instead of hard-failing :)

**Comment by fvanderbiest** [comment]
> nothing knows how to consume OGCAPI links in georchestra itself..unless i'm mistaken.

The datahub in its upcoming version will feature a simple API querier:
![image](https://github.com/georchestra/improvement-proposals/assets/265319/8530b2b3-965d-46c8-b0c0-28ba8effb0ef)

**Comment by fphg** [comment]
This one is nice if you intend to refurbish non-geo APIs into geoapis

> as a data platform admin, I configure vrt-bot to harvest remote datasets (eventually filtering them, or performing minor transformation steps). I'd like to serve these "remixed datasets" to my users with a standard's compliant API.

I definitively like this one 

> my org stores datasets in an internal Oracle database, which are not accessible to the general public. I'd like to foster local innovation by sharing this dataset more openly. (I'll set up an ETL job to push the selected datasets to a database connected with this API)

Thanks for the GIP

**Comment by pierrejego** [comment]
Really good news, thank you for this proposal !

**Comment by MaelREBOUX** [comment]
By now starts the vote period which will end at 2024-02-29 10h30.

**Comment by MaelREBOUX** [comment]
I could not be able to test. As I could see there is improvements to do on the code but the need to get this brick in georchestra is useful.

So : +1.

**Comment by MaelREBOUX** [comment]
This GIP is approved.

(forget to change the labels...)

**Comment by fvanderbiest** [comment]
Repository moved to https://github.com/georchestra/data-api
